feat: Replace changed files增加打印

diff --git a/.github/workflows/pr-viewer.yml b/.github/workflows/pr-viewer.yml
--- a/.github/workflows/pr-viewer.yml
+++ b/.github/workflows/pr-viewer.yml
@@ -43,7 +43,18 @@ jobs:
         if: ${{ env.GIT_DIFF_CONTENT }}
         run: |
           for file in ${{ env.GIT_DIFF_CONTENT }}; do
-            cp $file base-repo/$file
+            echo "Checking if $file exists..."
+            if [ -f "$file" ]; then
+              echo "$file exists. Copying to base-repo/$file..."
+              cp "$file" "base-repo/$file"
+              if [ $? -eq 0 ]; then
+                echo "Successfully copied $file to base-repo/$file"
+              else
+                echo "Failed to copy $file to base-repo/$file"
+              fi
+            else
+              echo "$file does not exist!"
+            fi
           done
 
       - name: Use Node.js 16.x
